name: Deploy Webhook

on:
  repository_dispatch:
    types:
      - webhook-one
      - webhook-two
      - webhook-develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Hello
        run: echo "Hello, I've been triggered by a webhook!"
      - name: Event Name
        run: |
          echo "Event triggered by $GITHUB_EVENT_NAME"
          echo "Dispatch type ${{ github.event.action }}"
      - name: Goodbye
        if: ${{ github.event.action == 'webhook-one' }}
        run: echo "Event one was called"
      - name: Adi√≥s
        if: ${{ github.event.action == 'webhook-two' }}
        run: echo "Event two was called"
      - name: Develop
        if: ${{ github.event.action == 'webhook-develop' }}
        run: echo "Event DEVELOP was called"
